### ISSUE TITLE
Tried to use ClientTimeoutInterval to trigger OnDisconnectedAsync handler, did not work.

### ISSUE THREAD

**Issue by arsalan-menhaj** [aspnet/Docs#10849]
As stated above, I had configured a ClientTimeoutValue in my application, and had expected that the OnDisconnectedAsync handler would be called on timeout. I had set the KeepAliveInterval to be longer than the ClientTimeoutValue in order to be able to test this. However, it seems the OnDisconnect handler was not triggered. Is there a different handler that would be able to capture this event? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Let me ask a few questions to figure out if we have an opportunity to improve the doc or the product.

> The server will consider the client disconnected if it hasn't received a message (including keep-alive) in this interval. 

Had you refrained from sending messages to the server for a period of time greater than the value of your `ClientTimeoutValue` setting or the `KeepAliveInterval` value? 

> It could take longer than this timeout interval for the client to actually be marked disconnected, due to how this is implemented. The recommended value is double the `KeepAliveInterval` value.

What is your `KeepAliveInterval` value and how long did you wait before presuming the `OnDisconnected` method would fire?

**Comment by bradygaster** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by hassanrazakhalid** [comment]
Hi
i am using DotnetCore 3.1
following are my server settings

```
services.AddSignalR(hubOptions =>
            {
                hubOptions.EnableDetailedErrors = true;
                hubOptions.KeepAliveInterval = TimeSpan.FromSeconds(20);
                hubOptions.ClientTimeoutInterval = TimeSpan.FromSeconds(10);
                //var x = hubOptions.KeepAliveInterval;
            });

public override async Task OnDisconnectedAsync(Exception exception)
        {
            _logger.LogInformation($"In  OnDisconnectedAsync");
            var removedPart = _connectioManager.RemoveConnection(Context.ConnectionId);
            _logger.LogInformation($"Removing Part {JsonSerializer.Serialize(removedPart)}");
            if (removedPart != null)  await BroadCastToDeviceParts(removedPart.DeviceId);
            
            await base.OnDisconnectedAsync(exception);
        }

```
I tried switching off Wifi of iPad completely. But still OnDisconnectedAsync is never called. I waited more than 5 mins but it should have called after 10sec. I am using microk8s on bare metal. I tried commenting out some settings in my ingress. Please let me know if more information is required.
```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-signalr
  # annotations:
  #   nginx.ingress.kubernetes.io/affinity: cookie
  #   nginx.org/websocket-services: "xtheia-go-signalr"
  #   nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  #   nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: "***"
    http:
      paths:
      - pathType: Prefix
        path: "/signalr"
        backend:
          service:
            name: xtheia-go-signalr
            port:
              number: 80
```
