### ISSUE TITLE
Create a page describing how to setup HTTPS

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#3310]
- How to create the certificate cross platform?
- How to configure Kestrel to use that certificate in production/development?
- How to make sure that certificate is trusted by the browser during development (like we do with the IIS Express certificate)?

**Comment by danroth27** [comment]
We also need to cover how to setup the dev certificate when using Docker in development:
* Create an application on Visual Studio using the MVC template.
* Run the app to ensure its working.
* Add docker support for the application through the tooling.
* Modify the dockerfile to expose the port 443 with
  EXPOSE 443
* Modify the docker-compose override file to map ports, volumes and environement variables as follows (this will all be unnecessary after docker tooling has support for HTTPS):
```yml
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost;http://localhost
      - ASPNETCORE_HTTPS_PORT=44349
    ports:
    # Replace the values on the left by the values on your launchSettings.json
      - "51217:80"
      - "44349:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/
```
* Export the HTTPS certificate into a PFX file using the dev-certs global tool to %APPDATA%/ASP.NET/Https/<<AppName>>.pfx using a password of your choice (recommended password new-guid on powershell)
* On your project, open user secrets and add the following configuration keys:
```json
{
    "Kestrel":{
        "Certificates":{
            "Default":{
                "Path":     "/root/.aspnet/https/<AppName>>.pfx",
                "Password": "<<Your-Password>>"
            }
        }
    }
}
```

* Run your application within the container.
* Navigate to the HTTP endpoint on your application
    * You should not see any warning about the HTTPS certificate being invalid.
    * You should be redirected to the HTTPS endpoint automatically.
