### ISSUE TITLE
How do we supply Docker Build arguments?

### ISSUE THREAD

**Issue by mohamedmansour** [aspnet/Docs#7160]
My docker build requires build arguments, how do we supply build arguments to build this?

In Console, I usually do `docker build --build-arg VSTS_TOKEN=foo`

When I add "args" in docker compose override, it says:

`Unsupported config option for services.web: 'args'`

```
version: '3.4'
services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    ports:
      - "8000:80"
    args:
      VSTS_TOKEN: foo
```

You can add args to the docker-compose.yml but not the override.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by mohamedmansour** [comment]
Was missing a "build" 

```
version: '3.4'
services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    ports:
      - "8000:80"
    build:
      args:
        VSTS_TOKEN: foo
```
