### ISSUE TITLE
Document StatusCodes and RedirectToWww methods

### ISSUE THREAD

**Issue by spacecat** [aspnet/Docs#8768]
I want to use             app.UseHttpsRedirection(); with a 301 permanent redirect.
I also want to redirect non www to www. 
How do I do this? Can you post an example Startup.cs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @spacecat ...

Yes, it seems strange now that I didn't link `StatusCodes`, so I'll do that shortly. You can find them all here :point_right: https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.statuscodes

Using the HTTPS Redirection Middleware approach (just handles HTTP -> HTTPS):

```csharp
services.AddHttpsRedirection(options =>
{
    options.RedirectStatusCode = StatusCodes.Status301MovedPermanently;
    options.HttpsPort = 443;
});  
```

For redirection (non-`www` to `www`), @clockworkmice just added it for [URL Rewriting Middleware](https://docs.microsoft.com/aspnet/core/fundamentals/url-rewriting), but it went under the radar when 2.1 came out and didn't get documented: See: https://github.com/aspnet/BasicMiddleware/pull/297

The API ref shows the three extension methods for `RewriteOptions`: One sets the status code to 308 (perm), one for 307 (temp), and one you can set whatever status code you want:

* `AddRedirectToWwwPermanent(RewriteOptions)` &ndash; Permanently redirects the request to the www subdomain if the request is non-www. [`Status308PermanentRedirect`]
* `AddRedirectToWww(RewriteOptions)` &ndash; Redirect the request to the www subdomain if the incoming request is non-www. [Serves `Status307TemporaryRedirect`.]
* `AddRedirectToWww(RewriteOptions, Int32)` &ndash; Redirect the request to the www subdomain if the incoming request is non-www. [You provide the status code.]

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.rewrite.rewriteoptions

Note also that URL Rewriting Middleware also has a way to handle the HTTPS redirection with its `AddRedirectToHttpsPermanent` option, so you could just use the URL Rewriting Middleware for both HTTP -> HTTPS and the non-`www` to `www` scenarios and not use the HTTPS Redirection Middleware.

Two doc updates on this issue that I'll do when I get back (I'm on vacation 🏖 for a few more days):

* I'll update this topic for the `StatusCodes`.
* I'll surface the `RedirectToWwwRule` in the URL Rewriting Middleware topic.

Thanks for opening this issue.

**Comment by spacecat** [comment]
Regarding the HTTPS Redirection Middleware.

My setup:
An AKS cluster
A default ASP.NET Core 2.1 Razor Pages app
An nginx ingress with a set of http rules

I'm trying the simplest scenario I could think of by just adding 

```
services.AddHttpsRedirection(options =>
{
    options.RedirectStatusCode = StatusCodes.Status301MovedPermanently;
    options.HttpsPort = 443;
}); 
```
to my default app.

Once all my pods have been redeployed I navigate to my site, http://www.mysite.com, and I get a ERR_TOO_MANY_REDIRECTS.

I think what is happening is that since I have an ingress with routing/http rules, that is forcing the URL to be rewritten twice. Once in NGINX and then again by ASP.NET Core. Ultimately resulting in an infinite redirect loop.

Could this be the case or am I missing something else?

Startup.cs

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace startpage
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddHttpsRedirection(options =>
            {
                options.RedirectStatusCode = StatusCodes.Status301MovedPermanently;
                options.HttpsPort = 443;
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseMvc();
        }
    }
}
```

Ingress.yml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysite-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - www.mysite.com
    - backend.mysite.com
    secretName: tls-secret
  rules:
  - host: www.mysite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: startpage-svc
          servicePort: 80
      - path: /blog
        backend:
          serviceName: blog-svc
          servicePort: 80
  - host: backend.mysite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blogcms-svc
          servicePort: 80
```
